# Header

menu:
  主页: /
  标签: /tags
  分类: /categories
  随笔: /notes
  归档: /archives

# SubNav  添加社交页面
subnav:
  github: https://github.com/YaoJusheng
  gitee: https://gitee.com/YaoJusheng  # 码云
  # jianshu: "#" #简书
  # cnblog: "#"
  #blog: "#"
  csdn: "https://blog.csdn.net/weixin_41599858"
  #rss: "#"
  # zhihu: "https://www.zhihu.com/people/qing-kuang-shu-sheng-78-59"
  #qq: "img/*.jpg"
  #weixin: "img/*.png"
  #weibo: "#"
  #douban: "#"
  #segmentfault: "#"
  # bilibili: "https://www.bilibili.com/"
  #acfun: "#"
  mail: "mailto:jusheng_yao@outlook.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

# RSS订阅(关于如何配置启用:https://www.jianshu.com/p/2aaac7a19736)
rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 / 设为 /blog/。
# 新版本已弃用，请在博客根目录文件进行配置
# root: /

# Content

# 文章太长，截断按钮文字
# excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
  # enable: true
  # per_page: true

# 文章结束语
end_message:
  enable: true
  default: 'The END'
  text: '本文已结束，感谢阅读!'

# Open link in a new tab | 是否在新窗口打开链接
open_in_new:
  article: true  # 文章链接
  menu: false   # 导航菜单
  subNav: false  # 子菜单

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: 'Thinks for your support!'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/alipay.jpg
# 微信二维码图片地址
weixin: /img/wechat.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

#是否开启分享
socialShare: true
#是否开启云标签
tagcloud: true

#是否开启捐赠
donate: true
#是否开启站内搜索
search: true

#是否开启最近通知
recent: true
recentContent: ''
#是否开启微简历
resume: true

# Miscellaneous (前两个是设置百度和谷歌搜索的，favicon设置标签页图标的)
# 百度统计
baidu_analytics: ''
google_analytics: ''

# 网站图标
favicon: /images/site-icon/ico/MrYao.ico

# 你的头像url
avatar: /images/avatar.jpg  

#是否开启分享
share_jia: true

# 评论： 1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment；6、Giteement ;7、gitalk ;8、valine ;9、utteranc
# 是否开启评论, 不需要使用某项，直接设置值为false，或注释掉
#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

# 3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

# 5、Gitment----基于GitHub的评论系统(关闭请设置gitment_owner为false)
# 关于如何集成:https://www.jianshu.com/p/ac7658cc912f
gitment_owner: false      # 你的 GitHub ID  e.g. YaoJusheng
# 是否使用官方js(false可以提升访问速度，本地修改过一部分的js，官方js可能会出现服务器不稳定，不太建议使用)
gitment_repo: 'yaojusheng.github.io'          #存储评论的 repo name(需要在Github创建)
gitment_oauth:
  client_id: '35890ce192840bd76bc6'           #client ID
  client_secret: '18b465f1ea803824fe0aef032d74ce6262df3b6e'       #client secret

# 6、Giteement----【国内用户建议使用这个，相对比较快】
# 关于如何集成:https://www.jianshu.com/p/f5c4633524c7
# 基于码云的评论系统(https://gitee.com/zhousiwei/giteement)
giteement:
  enable: false  # 是否启用码云评论系统
  # 是否使用官方js(false可以提升访问速度)
  remote: false
  redirect_uri: https://yaojusheng.gitee.io/blog/   # 应用回调地址(请和配置的第三方应用保持一致)
  # 不能更改(网上开源项目`https://github.com/Rob--W/cors-anywhere`作者提供的专门用来跨域服务器的配置)
  oauth_uri: https://cors-anywhere.herokuapp.com/https://gitee.com/oauth/token
  giteeID: yaojusheng  # 你的码云账号英文名
  # 存储评论的 repo name(需要在码云仓库创建公开仓库)
  repo: blog
  gitment_oauth:
    client_id: '08574314fd7e0914b566851ee1949fa8e0e7b6538f9b6e2cb742103f6a26cfc9'           #client ID
    client_secret: '7a058b4578762f4002ab6686e600693619778f435bff63a92325f846741290e3'       #client secret

# 7、gitalk评论
gitalk:
  enable:  false
  githubID:  YaoJusheng   
  repo:  'yaojusheng.github.io'
  ClientID:  '35890ce192840bd76bc6'
  ClientSecret:  '18b465f1ea803824fe0aef032d74ce6262df3b6e'
  adminUser:  YaoJusheng
  distractionFreeMode: true

# 8、valine 评论系统，到leancloud进行注册
# https://leancloud.cn/dashboard/login.html#/signup
valine:
 appid: 'oT30CtobWiSnNhMrBtXP9d0A-gzGzoHsz'  # Leancloud应用的appId
 appkey: 'oVHGMlRjJJyTXPLmyrGKrWFu'          # Leancloud应用的appKey
 verify: false      # 验证码
 notify: true       # 评论回复提醒
 avatar: wavatar        # 评论列表头像样式（https://valine.js.org/avatar）mm
 placeholder: 有话要说？ # 评论框占位符

# 9、utteranc评论： https://utteranc.es (参数配置详见主页) 替换 gitment、gitalk
utterance:
  enable: true
  repo: 'yaojusheng/yaojusheng.github.io'     #仓库名字,格式：你的用户ID/仓库名称，如：blog/utterance_repo
  issue_term: 'title'            #映射配置
  theme: 'github-light'          #主题

# Daovoice DaoCloud 在线沟通
daovoice: true 
daovoice_app_id: "6d0092ef"   # 6d0092ef/ eb35ef31

# 访问量统计功能(不蒜子)
busuanzi:
  enable: true
  total_visitors: true
  total_visitors_icon: user
  total_views: true
  total_views_icon: eye
  post_views: true
  post_views_icon: eye

# 网易云音乐插件
music:
  enable: true
  # 播放器尺寸类型(1：短尺寸、2：长尺寸)
  type: 2
  id: 27580009  # 网易云分享的音乐ID(更换音乐请更改此配置项)
  autoPlay: true  # 是否开启自动播放
  # 提示文本(关闭请设置为false)
  text: '悠扬的旋律，为谁而敲响！'

# 页面点击小红心
clickLove:
  # (关闭请设置为false)
  enable: true

# 心知天气
xinzhi_weather: true

# 飘雪特效1
# https://github.com/MlgmXyysd/snow.js
snow: true
# 雪花特效2
snow2: true

# https://github.com/hustcc/canvas-nest.js
# 配置详见： https://github.com/hustcc/canvas-nest.js#configuration
# 动态线条效果，会向鼠标集中
canvas_nest:
  enable: true
  color: '229, 253, 13'        # color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  pointColor: '59, 11, 235'     # color of points, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  opacity: '0.9'               # the opacity of line (0~1), default: 0.5.
  count: '96'                  # the number of lines, default: 99.
  zIndex: '-1'                 # z-index property of the background, default: -1.

# GitHub Ribbons(https://github.blog/2008-12-19-github-ribbons/)
github:  #false   
  # (关闭请设置为false)
  url: https://github.com/litten/hexo-theme-yilia

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#ccc,#000)'
  # 左侧头像板块动态图效果
  gif:
    # 是否启用
    enable: true
    # 自定义背景图路径(默认可以不设置，提供默认背景图biubiubiu.gif)
    path: /img/back-02.gif

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

# 友情链接
friends:
  Google搜索: 
    url: https://www.google.com/
    ico: /images/ico/google_favicon.ico
    description: 最受欢迎的搜索引擎，国内使用可用代理或安装助手
  Bing搜索: 
    url: https://cn.bing.com/
    ico: /images/ico/biying_favicon.ico
    description: 必应搜索，一款好用的搜索引擎
  Translate: 
    url: https://translate.google.cn/
    ico: /images/ico/fanyi_favicon.ico
    description: 谷歌翻译
  bilibili: 
    url: https://www.bilibili.com/
    ico: /images/ico/bili_favicon.ico
    description: 技术视频网站
  知乎: 
    url: https://www.zhihu.com/
    ico: /images/ico/zhihu_favicon.ico
    description: 知识、技术交流平台
  在线工具: 
    url: https://tool.lu/
    ico: /images/ico/onlinetool.ico
    description: 全面多样化的开发、站长类工具
  百度字体编辑器: 
    url: http://fontstore.baidu.com/static/editor/index.html
    ico: /images/ico/font_favicon.ico
    description: 可制作图形文字，减少字体体积
  绘图draw: 
    url: https://www.draw.io/
    ico: /images/ico/draw_favicon.ico
    description: 一款在线绘制流程图的网页工具
  百度脑图: 
    url: https://naotu.baidu.com/home
    ico: /images/ico/naotu_favicon.ico
    description: 一款可替代XMind的在线思维导图工具
  
  更多: '#'

# Local search(本地搜索)
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  enable: true

# 代码高亮
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# https://github.com/willin/hexo-wordcount
# 是否开启字数统计(关闭请设置enable为false)
# 也可以单独在md文件里Front-matter设置`no_word_count: true`属性，来自定义关闭字数统计
word_count:
  enable: true
  # 只在文章详情显示(不在首页显示)
  only_article_visit: true

# 关于我
aboutme: <div style="text-align:center"><span style="color:yellow;font-size:20px;">主要涉及技术：</span><br><br><div style="color:lightblue;">Python开发<br>PHP、前端开发<br>Ruby开发、Linux<br><br>联系QQ:870560379<br><br>很惭愧...<br>只做了一点微小的工作<br>谢谢大家!</div></div>

# 页脚 Litten
# 帮助我们让更多人可以更方便使用Hexo，请尽量不要修改此主题配置
pageFooter:
  litten: GitHub:<a href="https://github.com/litten/hexo-theme-yilia" target="_blank">hexo-theme-yilia</a>

# 开启百度站长平台自动推送(https://ziyuan.baidu.com/linksubmit/index)
baidu_push: false

# Progress Bar | 页面加载进度条
# Demo: http://github.hubspot.com/pace/docs/welcome/
# type: barber-shop|big-counter|bounce|center-atom|center-circle|
#       center-radar|center-simple|corner-indicator|flash|flat-top|
#       loading-bar|mac-osx|minimal
# color: black|blue|green|orange|pink|purple|red|silver|white|yellow|
progressBar:
  enable: true
  type: 'minimal'  # Keep Quotes | 保留引号避免出错(某些type会导致样式重叠排版错误)
  color: blue

# 版权声明
# 版权声明type设定：0-关闭版权声明； 1-文章对应的md文件里有copyright: true属性，才有版权声明； 2-所有文章均有版权声明
copyright:
  copyright_type: 2
  licensee_url: https://creativecommons.org/licenses/by-nc-sa/4.0/        #当前应用的版权协议地址。
  licensee_name: 'CC BY-NC-SA 4.0'                                        #版权协议的名称
  licensee_alias: '知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议'       # alias别名
  # https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png
  licensee_img: /images/copyright.png                            #版权协议的Logo (/images/copyright.png)
  # 版权声明自定义文本(关闭请设置为false)
  copyright_text: 

# 网站成立年份(默认为 2020，若填入年份小于当前年份，则显示为 2019-2020 类似的格式)
since: 2020