# Header

menu:
  主页: /
  随笔: /tags/随笔/index.html
  归档: /archives/index.html

# SubNav  添加社交页面
subnav:
  github: https://github.com/YaoJusheng
  # weibo: "#"
  # rss: "#"
  zhihu: https://www.zhihu.com/people/qing-kuang-shu-sheng-78-59
  csdn: https://blog.csdn.net/weixin_41599858
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  bilibili: https://www.bilibili.com/
  #acfun: "#"
  mail: "mailto:jusheng_yao@outlook.com"
  #facebook: "#"
  # google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏 (图片地址是在 source 目录下的，所以要在source下创建文件夹，然后把资源放进去)
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '坚持原创技术分享，您的支持将鼓励我继续创作！'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous  (前两个是设置百度和谷歌搜索的，favicon设置标签页图标的)
baidu_analytics: ''
google_analytics: ''
favicon: /images/favicon.png

# 头像url
avatar: /img/avatar.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: YaoJusheng                     #你的 GitHub ID
gitment_repo: 'YaoJusheng.github.io'          #存储评论的 repo
gitment_oauth:
  client_id: '35890ce192840bd76bc6'           #client ID
  client_secret: '18b465f1ea803824fe0aef032d74ce6262df3b6e'       #client secret

#6、gitalk评论
gitalk:
  enable:  true
  githubID:  YaoJusheng   
  repo:  'YaoJusheng.github.io'
  ClientID:  '35890ce192840bd76bc6'
  ClientSecret:  '18b465f1ea803824fe0aef032d74ce6262df3b6e'
  adminUser:  YaoJusheng
  distractionFreeMode: true

# Show Views/Visitors of the website/page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi
# 阅读计数
busuanzi_count:
  enable: true
  total_visitors: true
  total_visitors_icon: user
  total_views: true
  total_views_icon: eye
  post_views: true
  post_views_icon: eye

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  Baidu: https://www.baidu.com/
  Google: https://www.google.com/
  Bing: https://cn.bing.com/
  Translate: https://translate.google.cn/
  更多: '#'

# Local search(本地搜索)
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  enable: true

# 代码高亮
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
aboutme: 很惭愧<br><br>只做了一点微小的工作<br>谢谢大家